{
 "title": "IxiaChassisMonitoring",
 "description": "IxiaChassisMonitoring for Port Usage and CPU/Memory Utilization",
 "time": { "from": "2025-11-09T21:39:14.317Z", "to": "2025-11-09T22:09:14.317Z" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "ChassisIP", "label": "ChassisIP", "query": "10.36.75.205" }
  ]
 },
 "panels": [
  {
   "title": "PortUsage",
   "type": "state-timeline",
   "description": "PortUsage. Enter your Chassis IP to view metrics for chassis of interest.",
   "gridPos": { "h": 20, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"ixosChassisStatistics\")\n  |> range(start: -24h)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"portUtilization\")\n  |> filter(fn: (r) => r[\"chassis\"] == \"${ChassisIP}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"owner\")\n\n"
    }
   ]
  },
  {
   "title": "Link Up/Down",
   "type": "state-timeline",
   "description": "Link Up/Down",
   "gridPos": { "h": 20, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"ixosChassisStatistics\")\n  |> range(start: -24h)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"portUtilization\")\n  |> filter(fn: (r) => r[\"chassis\"] == \"${ChassisIP}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"linkState\")"
    }
   ]
  },
  {
   "title": "CPU/Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "cpu_utilization{chassis=\"$ChassisIP\"}",
     "legendFormat": "% CPU Util -  {{chassis}}"
    },
    {
     "expr": "memory_utilization{chassis=\"$ChassisIP\"}",
     "legendFormat": "% memory Util -  {{chassis}}"
    }
   ]
  },
  {
   "title": "Port Traffic Transmit",
   "type": "state-timeline",
   "description": "Link Up/Down",
   "gridPos": { "h": 16, "w": 23, "x": 0, "y": 34 },
   "targets": [
    {
     "query": "from(bucket: \"ixosChassisStatistics\")\n  |> range(start: -24h)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"portUtilization\")\n  |> filter(fn: (r) => r[\"chassis\"] == \"${ChassisIP}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"transmitState\")"
    },
    {
     "query": "from(bucket: \"ixosChassisStatistics\")\n  |> range(start: -24h)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"portUtilization\")\n  |> filter(fn: (r) => r[\"chassis\"] == \"${ChassisIP}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"owner\")\n\n"
    }
   ]
  }
 ]
}