{
 "title": "IxOSSensorData",
 "description": "IxOSSensorData",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "ChassisIP", "label": "ChassisIP", "query": "10.36.75.205" }
  ]
 },
 "panels": [
  {
   "title": "Power Supply",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ixos_sensor_current_amperes{sensor_name=~\"PS.*\", chassis=\"$ChassisIP\"}",
     "legendFormat": "{{chassis}} : {{ sensor_name }}"
    }
   ]
  },
  {
   "title": "Chassis CPU",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 12, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ixos_sensor_temperature_celsius{sensor_name=~\"Core.*\", chassis=\"$ChassisIP\"}",
     "legendFormat": "{{chassis}}: {{sensor_name}}"
    }
   ]
  },
  {
   "title": "Fan Speed % of maximum",
   "type": "gauge",
   "description": "Fan Speed % of maximum",
   "gridPos": { "h": 15, "w": 22, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ixos_sensor_fan_speed_ratio{chassis=\"$ChassisIP\"} * 100",
     "legendFormat": "{{chassis}} : {{ sensor_name }}"
    }
   ]
  }
 ]
}